name: Shortpost AI Auto-Translation

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'src/content/shortpost/**'

jobs:
  translate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Environment Setup
        uses: ./.github/actions/setup

      - name: Install dependencies in submodule
        working-directory: ./gpt-markdown-translator
        run: pnpm install --frozen-lockfile

      - name: Create LFS file list
        run: git lfs ls-files --long | cut -d ' ' -f1 | sort > .lfs-assets-id

      - name: LFS Cache
        uses: actions/cache@v4
        with:
          path: .git/lfs/objects
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
          restore-keys: |
            ${{ runner.os }}-lfs-

      - name: Git LFS Pull
        run: git lfs pull

      - name: Translation
        working-directory: ./gpt-markdown-translator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
        run: pnpm run translate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'feat(shortpost): auto-translate'
          title: '[Bot] Shortpost AI Auto Translate'
          body: |
            # Auto-generated by GitHub Action
          labels: |
            auto-translate
          branch: auto-translation
          delete-branch: false
          base: main
